name: Docker_without_LS_arm

on:
  push:
    branches: [ arm ]

  schedule:
    - cron:  '0 2 * * *' # at the end of every day

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  cancel:

    name: Cancel Previous Runs
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_CI: true
      TOKEN: ${{ secrets.DOCKERHUB }}
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch the whole history

      - uses: uraimo/run-on-arch-action@v2
        name: Docker
        with:
          arch: aarch64
          distro: ubuntu20.04

          run: ./.ci/docker_without_linux_setup_arm.sh
